version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.1
    steps:
      - checkout
      - run:
          name: bundle install
          command: 'bundle install --path vendor/bundle'
      - run:
          name: rspec
          command: 'bundle exec rspec'
      - run:
          name: danger
          command: 'bundle exec danger'
  deploy:
    docker:
      - image: ruby:2.3.1
    steps:
    - checkout
    - deploy:
        command: |
          cd style-guide
          bundle install --path ../vendor/bundle
          apt-get update && apt-get install -y nodejs
          bundle exec middleman build
          bundle exec middleman s3_sync
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
