source 'https://rubygems.org'

### Middleman/Style Guide Gems
######

gem "middleman", "3.3.5"
gem 'whitespace', '2.0.4'

gem 'bootstrap-sass', '~> 3.1.1'
gem 'middleman-sprockets', '3.3.2' # https://github.com/middleman/middleman/issues/1265
gem 'middleman-bootstrap-navbar', '~> 2.0'

# Live-reloading plugin
gem "middleman-livereload"
gem "middleman-minify-html"
gem 'middleman-s3_sync'
gem 'fog'
gem 'nokogiri'

gem 'haml'
gem 'bourbon'
gem 'neat'
